version: "3.9"
services:
  api:
    image: build2024/app:latest
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL
  frontend:
    image: build2024/web:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL